site_name: ChemKit Documentation
site_url: http://chem-kit.metwork.science

markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - markdown_include.include


plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_root_heading: false
            show_root_toc_entry: false
            show_root_full_path: false
            show_source: false
            show_if_no_docstring: false
            group_by_category: false
            heading_level: 3
      watch:
        - chem_kit
  - mknotebooks

theme:
  name: material

extra_css:
  - custom.css
